odo/values.yaml
Odo was dying on OOM errors for even relatively small shapefile conversions - this is a bandaid fix to help us get around these errors.
smartcitiesdata/odo#17
co-authored-by: Richard Jones <rajones@hntb.com>
=> Increasing memory for odo

andi/templates/deployment.yaml
The vm_args that distillery uses to release an app are expecting the $NODE_IP to be in the container environment variables in order to set a proper hostname for the erlang node.
=> Fixing andi hostname

andi/Chart.yaml, andi/templates/deployment.yaml, andi/templates/secrets.yaml, andi/values.yaml
Adds the ability to define a signing salt environment variable for the andi chart and provides a default value so the app doesn't blow up in a development environment if the secret isn't already injected into the cluster by other, out-of-band means.
=> Adding andi liveview salt secret to chart

andi/templates/deployment.yaml, andi/templates/secrets.yaml
secrets and other resources need to be DNS-1123 compatible, so no underscores, please and thank you.
=> rename andi secret to be k8s compatible

charts/kafka/Chart.yaml, charts/kafka/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
These map kafka containers to specific EC2s that we configured for SCOS. These mappings should be in the deploy repo, instead of the public chart.
We noticed because, when deploying elsewhere (where we don't have these specific EC2s) we were unable to override these config values. (Due to a helm bug: https://github.com/helm/helm/issues/9136)
Regardless, they should be moved from the public chart to the deploy repo since they're deployment specific.
=> Remove SCOS affinity and tolerations from public chart: in deploy repo

.github/workflows/release.yml, .gitignore, charts/urban-os/Chart.lock
Fix for an issue where the kafka dependencies were not getting packaged
=> dependency fix

charts/kafka/Chart.yaml, charts/kafka/templates/kafka.yml, charts/urban-os/Chart.yaml
These changes support single node clusters like minikube, and updates the node selector used by strimzi to be more in line with current k8s versions.
=> changes to support single node clusters

charts/discovery-api/Chart.yaml, charts/discovery-api/templates/deployment.yaml, charts/discovery-api/values.yaml, charts/discovery-streams/Chart.yaml, charts/discovery-streams/templates/deployment.yaml, charts/discovery-streams/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
Adds default values for raptor url to the global auth block
=> Default raptor_url set in charts

charts/andi/Chart.yaml, charts/urban-os/Chart.lock
Forgotten Andi chart version increase in PR #326 is causing charts deployments to fail.
PR #326: https://github.com/UrbanOS-Public/charts/pull/326
Failures: (Line 48 of "run chart releaser" step) https://github.com/UrbanOS-Public/charts/runs/4768298301?check_suite_focus=true#step:6:48
=> Andi Version Bump (Forgotten in PR #326)

charts/andi/Chart.yaml, charts/andi/templates/deployment.yaml, charts/andi/templates/ingress.yaml, charts/andi/templates/secrets.yaml, charts/andi/values.yaml, charts/discovery-api/templates/deployment.yaml, charts/discovery-api/values.yaml, charts/discovery-ui/templates/ingress.yaml, charts/discovery-ui/values.yaml, charts/forklift/templates/deployment.yaml, charts/forklift/values.yaml
(Individual commits are well documented)
- Add Redis SSL Values
- New Postgres + Bucket Values
- Optional ingress
- AWS Secrets able to be set from global, documented as such in values file.
- Made sure discovery-api behaves the same way / is documented the same
- Altered some AWS forklift values so that it aligns with the way AWS values are configured elsewhere
=> Redis ssl andi

charts/monitoring/Chart.yaml, charts/urban-os/Chart.lock
=> Bumping monitoring version because odo is gone

charts/valkyrie/Chart.yaml, charts/valkyrie/templates/deployment.yaml, charts/valkyrie/values.yaml
Add the same redis ssl config that other apps have.
=> Add redis ssl config, like alchemist and the rest

charts/alchemist/Chart.yaml, charts/alchemist/templates/cluster-rbac.yaml, charts/andi/Chart.yaml, charts/andi/templates/rbac.yaml, charts/discovery-api/Chart.yaml, charts/discovery-api/templates/rbac.yaml, charts/discovery-streams/Chart.yaml, charts/discovery-streams/templates/rbac.yaml, charts/forklift/Chart.yaml, charts/forklift/templates/rbac.yaml, charts/kafka/Chart.yaml, charts/kafka/templates/kafka-patcher.yaml, charts/kafka/templates/kafka.yml, charts/kafka/values.yaml, charts/raptor/Chart.yaml, charts/raptor/templates/rbac.yaml, charts/raptor/values.yaml, charts/reaper/Chart.yaml, charts/reaper/templates/rbac.yaml, charts/urban-os/Chart.yaml, charts/valkyrie/Chart.yaml, charts/valkyrie/templates/cluster-rbac.yaml
Big changes:
1. Kafka version update to support k8s 1.22
2. ApiVersion updates for the same reason
=> Openshift chart updates

charts/kafka/Chart.yaml, charts/kafka/templates/kafka.yml, charts/kafka/values.yaml, charts/urban-os/Chart.lock
=> add zookeeperResources to kafka chart

.gitignore, charts/discovery-ui/Chart.yaml, charts/discovery-ui/values.yaml, charts/kafka/Chart.yaml, charts/kafka/templates/kafka.yml, charts/kafka/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
- Adding new commands to the local-deploy-script ensures that the strimzi dependencies will always be present 
- Renames zookeeperResources to zookeeper.resources
=> Adjust zookeeperResources to zookeeper.resources

charts/discovery-ui/Chart.yaml, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/templates/deployment.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
[Ticket Link](https://app.zenhub.com/workspaces/mdot-615b97c1a5fde400126174f8/issues/urbanos-public/internal/711)
- Uses config maps to configure nginx server properties. This was previously done in the discovery_ui image itself.
- Uses config maps for the config.js values as well.
=> Use configmap for nginx ubi image configuration

.github/pull_request_template.md, charts/forklift/Chart.yaml, charts/forklift/README.md, charts/forklift/templates/deployment.yaml, charts/forklift/values.yaml, charts/urban-os/Chart.lock
Forklift:
- Removes "special compaction" related values as that is now the default
- Adds "overwrite_mode" as an option
=> Remove values related to compaction 2.0 opt in + overwrite_mode

charts/kubernetes-data-platform/Chart.yaml, charts/urban-os/Chart.lock, charts/vault/Chart.yaml
- Add chart values that were forgotten in https://github.com/UrbanOS-Public/charts/pull/359. CI/CD is failing due to chart version conflicts.
=> Up previously forgotten chart versions

charts/forklift/Chart.yaml, charts/forklift/README.md, charts/forklift/templates/deployment.yaml, charts/forklift/values.yaml, charts/urban-os/Chart.lock
=> Remove compaction schedule value from forklift chart values

.github/workflows/release.yml, charts/urban-os/Chart.yaml
- [ - ] Did you up the relevant chart version numbers? (If appropriate)
- [ - ] If chart values added, were default values provided in the chart? (Will `helm template` pass?)
=> Adding dependency update to persistence within github action releases

charts/andi/Chart.yaml, charts/andi/README.md, charts/andi/templates/deployment.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> Fix andi charts

charts/andi/Chart.yaml, charts/andi/README.md, charts/andi/templates/deployment.yaml, charts/andi/values.yaml, charts/sauron/Chart.yaml, charts/sauron/README.md, charts/sauron/values.yaml, charts/urban-os/Chart.lock
=> add primaryColor to theme

charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> version bump urbanos

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
- ~~[ ] If chart values added, were default values provided in the chart? (Will `helm template` pass?)~~
- ~~[ ] Do you have git hooks installed? (See README.md to install)~~
- ~~[ ] If references to external charts were added:~~
- ~~[ ] Was the github release action updated to `helm update {new_thing}` it's dependencies?~~
- ~~[ ] Was the deploy repo `-u` flag updated to `helm update {new_thing}` to ensure it's not left out of deployments?~~
=> 837 configurable logo

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> add header title for discovery-ui

.github/pull_request_template.md, charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/templates/deployment.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
- DiscoveryUI Config Map is now mounted to the proper location for nginx to utilize, so the default config.js for local development will be correctly overridden by chart values
- Missing configmap wiring for Header title is now included
- Remove stale nginx conf that was not in use
- Added a single example footer link as the default
=> Update DiscoveryUI Configmap to mount at the proper location

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml
Add env variable for primary color in discovery ui
=> 838: add primary color to discovery ui chart

charts/urban-os/Chart.lock
=> helm dependency update - 838

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
~~- [] Do you have git hooks installed? (See README.md to install)~~
~~- [] If references to external charts were added:~~
~~- [ ] Was the github release action updated to `helm update {new_thing}` it's dependencies?~~
~~- [ ] Was the deploy repo `-u` flag updated to `helm update {new_thing}` to ensure it's not left out of deployments?~~
=> added DISC_UI_URL to discovery_ui

charts/andi/Chart.yaml, charts/andi/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
Changing Andi defaults to be more standardized, non-test text.
~- [ ] If chart values added, were default values provided in the chart? (Will `helm template . -f values.yaml` pass?)~
~- [ ] If references to external charts were added:~
~- [ ] Was the github release action updated to `helm update {new_thing}` it's dependencies?~
~- [ ] Was the deploy repo `-u` flag updated to `helm update {new_thing}` to ensure it's not left out of deployments?~
=> Changing footer defaults for Andi

charts/andi/Chart.yaml, charts/andi/README.md, charts/kafka/Chart.yaml, charts/kafka/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Bumped versions of kafka, andi, and urban-os
=> Bumped all versions included in the release tangle

charts/andi/Chart.yaml, charts/andi/README.md, charts/andi/templates/secrets.yaml, charts/andi/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Ticket Link NA
- Similar to the existing functionality where the auth0 secret can optionally be managed / created by helm, this adds that functionality to the aws secrets that andi utilizes.
- Corrected raptor to andi in an andi comment
Confirmed with a helm diff that this will not have effects on the product environment
=> Andi AWS secret optional to allow for pre-created secrets

charts/andi/Chart.yaml, charts/andi/README.md, charts/andi/templates/deployment.yaml, charts/andi/values.yaml, charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
~~- [ ] Do you have git hooks installed? (See README.md to install)~~
~~- [ ] If references to external charts were added:~~
~~- [ ] Was the github release action updated to `helm update {new_thing}` it's dependencies?~~
~~- [ ] Was the deploy repo `-u` flag updated to `helm update {new_thing}` to ensure it's not left out of deployments?~~
=> added footer_left_side_link to discoveryUI and ANDI

charts/sauron/Chart.yaml, charts/sauron/README.md, charts/sauron/templates/sauron-commands.yaml
Ticket: NA
Fixed typo in sauron chart so that object key and secret aren't flipped
=> Correct flipped secret + key

.github/workflows/release.yml
Added hashicorp as a dependency for vault chart
=> Added hashicorp as a dependency for vault chart

charts/andi/Chart.yaml, charts/andi/README.md, charts/persistence/Chart.yaml, charts/persistence/README.md, charts/reaper/Chart.yaml, charts/reaper/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Bumped versions that are not releasing correctly in github actions
=> Bumped tangled versions

charts/sauron/Chart.yaml, charts/sauron/templates/cron.yaml, charts/sauron/templates/sauron-commands.yaml, charts/sauron/values.yaml
=> add minio env vars

charts/discovery-ui/Chart.yaml, charts/kafka/Chart.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
=> Up chart version

charts/discovery-api/Chart.yaml, charts/discovery-api/README.md, charts/discovery-api/templates/deployment.yaml, charts/discovery-api/values.yaml, charts/discovery-streams/Chart.yaml, charts/discovery-streams/README.md, charts/discovery-streams/templates/deployment.yaml, charts/discovery-streams/values.yaml, charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml, charts/kafka/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md, charts/urban-os/values.yaml
Add require_api_key value to charts which will enable/disable users from viewing public datasets without logging in
=> Discovery UI require login

charts/urban-os/Chart.yaml, charts/urban-os/README.md, charts/urban-os/templates/minio-secrets.yaml
Added conditional to minio secrets so they are not generated if minio is disabled
=> Added conditional to minio secrets

charts/sauron/Chart.yaml, charts/sauron/README.md, charts/sauron/templates/cron.yaml, charts/sauron/values.yaml
Added minio endpoint as a sauron environment variable
=> Added minio endpoint as a sauron environment variable

charts/discovery-api/Chart.yaml, charts/discovery-api/README.md, charts/discovery-streams/Chart.yaml, charts/discovery-streams/README.md, charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/kafka/Chart.yaml, charts/kafka/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Bumped all tangled versions and helm dep up for each in case its needed
=> Bumped all tangled versions and helm dep up for each in case its needed

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Adding new environment variables so discovery ui/api/streams can have different urls. Leaving old environment variables in place for now to not break existing code. Will remove in a separate PR once other changes are merged.
~- [ ] If global values were altered, are they included as chart default values?~
~- [ ] Are they also specified in the urbanos chart values file?~
~- [ ] If references to external charts were added:~
~- [ ] Was the github release action updated to `helm update {new_thing}` it's dependencies?~
~- [ ] Was the deploy repo `-u` flag updated to `helm update {new_thing}` to ensure it's not left out of deployments?~
=> Adding new environment variables with placeholders

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Adding new environment variables for urls to discovery ui template.
- [ x If charts within the urban-os chart (andi, etc) have been updated, have you run `helm dependency update` in /charts/urban-os and commited the Chart.lock file?
=> Add new url variables to template

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> update chart for FF

charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Remove old environment variables for referencing discovery api/ui/streams now that the new ones are being used.
~- [] If chart values added, were default values provided in the chart? (Will `helm template . -f values.yaml` pass?)~
~- [ ] Do you have git hooks installed? (See README.md to install)~
~- [ ] If global values were altered, are they included as chart default values?~
~- [ ] Are they also specified in the urbanos chart values file?~
~- [ ] If references to external charts were added:~
~- [ ] Was the github release action updated to `helm update {new_thing}` it's dependencies?~
~- [ ] Was the deploy repo `-u` flag updated to `helm update {new_thing}` to ensure it's not left out of deployments?~
=> 925 remove old vars

.github/pull_request_template.md, charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/discovery-ui/templates/configs.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Accidentally removed the if clause in the last PR around discovery ui's contribute host variable. Putting it back.
=> Putting back mistakenly removed if clause

charts/urban-os/Chart.yaml, charts/urban-os/templates/auth0-config.yaml, charts/urban-os/values.yaml
Adding Raptor as a client to the auto-generated auth0 config. While doing this I noticed that aspects of the URLs for Andi and Discovery UI were hardcoded to specific subdomains which aren't relevant for all. Now these rely on a chart variable for the subdomain. I was originally going to put the subdomain under the relevant app (so it would be something like discovery-api.subdomain) rather than global (global.subdomains.discoveryApi) but helm template doesn't like the dashes in keys in the templated auth0 config. Instead they're under global.subdomains, which does have the advantage of all being in one place.
I didn't add callbacks to the Raptor client because those are urls which Auth0 calls after authentication, but in Raptor's case it's just doing a synchronous web call for …
=> Add Raptor client, make auth0 template for configurable

charts/andi/Chart.yaml, charts/andi/README.md, charts/andi/templates/deployment.yaml, charts/andi/values.yaml, charts/sauron/README.md, charts/urban-os/Chart.lock, charts/urban-os/README.md
Added Secondary, Success, and Error Colors
=> added secondary, success, and error colors to charts

charts/andi/Chart.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
=> bumped versions to untangle

charts/andi/Chart.yaml, charts/andi/templates/deployment.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
=> Low contrast andi

charts/discovery-ui/Chart.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
Just changing the default color scheme in discovery_ui to have higher contrast against white text / backgrounds
=> Increase contrast in discovery_ui via primary color

charts/andi/README.md, charts/discovery-ui/README.md, charts/discovery-ui/values.yaml, charts/kafka/README.md, charts/urban-os/README.md
Previous PR didn't update the helm-docs. Turns out I had a different pre-commit hook, so the script that is supposed to add a pre-commit that updates the docs didn't add the hook.
=> update charts readme for primary color in disc-ui

charts/andi/Chart.yaml, charts/andi/templates/deployment.yaml, charts/andi/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
Add secureCookie property to allow toggling of secure cookies in different environments
=> 1012 add secureCookie property to andi

charts/andi/Chart.yaml, charts/andi/README.md, charts/discovery-ui/Chart.yaml, charts/discovery-ui/README.md, charts/sauron/Chart.yaml, charts/sauron/README.md, charts/urban-os/Chart.lock
=> Bumped versions blocking ci

charts/urban-os/Chart.yaml
In the previous merge the github action for releasing workflow failed due to a typo error on urbanos/Chart.yaml which is fixed in this PR
=> 962 Define test trigger fix

charts/urban-os/Chart.lock
PR for fixing typo error on Chart.lock for performancetesting
=> fixing typo error on Chart.lock for performancetesting

charts/performancetesting/templates/cron.yaml
updating cron.yaml file sintax error
=> updating cron.yaml file sintax error

charts/performancetesting/Chart.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
updating version on performance test chart
=> updating version on performance test chart

charts/performancetesting/Chart.yaml, charts/performancetesting/templates/cron.yaml, charts/performancetesting/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/values.yaml
The enviroment variables were modified
=> US#1036-Performance-testing-image-issues

charts/kafka/Chart.yaml, charts/kafka/README.md, charts/monitoring/Chart.yaml, charts/monitoring/README.md, charts/performancetesting/Chart.yaml, charts/performancetesting/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> bumped all tangled versions

charts/andi/Chart.yaml, charts/andi/README.md, charts/andi/templates/deployment.yaml, charts/andi/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md, charts/urban-os/values.yaml
Added require_admin_api_key for andi
=> Added require_admin_api_key for andi

.gitignore, charts/monitoring/Chart.yaml, charts/monitoring/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> Monitoring dependencies

charts/discovery-api/Chart.yaml, charts/discovery-api/README.md, charts/discovery-api/templates/deployment.yaml, charts/discovery-api/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> Discovery api host config

.github/workflows/release.yml, charts/monitoring/Chart.yaml, charts/monitoring/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> Updating monitoring chart in github actions

charts/kafka/Chart.yaml, charts/kafka/README.md, charts/kafka/templates/kafka-exporter/scraper.yaml, charts/kafka/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Created a cron job that checks kafka-exporter and logs the metrics.
=> Add kafka scraper to kafka exporter

charts/sauron/Chart.yaml, charts/sauron/README.md, charts/sauron/templates/sauron-commands.yaml
Removing the instances of a hard-coded namespace.
=> Sauron remove specific namespace

charts/andi/Chart.yaml, charts/andi/templates/deployment.yaml, charts/andi/values.yaml, charts/discovery-ui/Chart.yaml, charts/discovery-ui/templates/configs.yaml, charts/discovery-ui/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml
Modified charts to include custom favicon
=> Modified charts to include custom favicon

charts/andi/Chart.yaml, charts/andi/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Incrementing to 1.13.51 to untangle releases
=> Updating version to 1.13.51 to trigger release

charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md, charts/urban-os/values.yaml
- Upgraded minio operator and tenant to 5.0.6
- Default disable Minio Browser Login Animation so that port forwarding works
=> Upgraded minio to 5.0.6

charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Drop back down to major version 7 but upgrade to the latest minor version, which should include the kube api update we need but won't break security like v8
=> change elasticsearch chart to latest version of v7

charts/kafka/Chart.yaml, charts/kafka/README.md, charts/persistence/Chart.yaml, charts/persistence/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> Revert and bump minio

charts/persistence/Chart.yaml, charts/persistence/README.md, charts/persistence/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
=> remove deprecated trino configs

charts/kafka/Chart.lock, charts/kafka/Chart.yaml, charts/kafka/README.md, charts/kafka/values.yaml, charts/persistence/Chart.yaml, charts/persistence/README.md, charts/persistence/values.yaml, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
Kafka, Strimzi, Minio, and Metastore version upgrades
=> Latest updates after debugging sessions

charts/urban-os/Chart.lock
=> update chart lock

charts/alchemist/Chart.yaml, charts/alchemist/README.md, charts/urban-os/Chart.lock, charts/urban-os/Chart.yaml, charts/urban-os/README.md
bump alchemist version to bring in memory changes
=> bump alchemist version to bring in memory changes
