streisand/values.yaml

co-authored-by: Sukaant Chaudhary <sukaant.chaudhary@gmail.com>

Fix Streisand Kafka broker value defaults

---

kubernetes-data-platform/templates/presto/coordinator-deployment.yaml
kubernetes-data-platform/templates/presto/presto-configs.yaml
kubernetes-data-platform/templates/presto/worker-deployment.yaml
kubernetes-data-platform/values.yaml

co-authored-by: Nathaniel Stevens <nstevens@pillartechnology.com>
Keep in mind that this assumes a fairly robust machine running minikube.

Updates kdp to be minikube friendly

---

reaper/templates/deployment.yaml
reaper/values.yaml

co-authored-by: Sukaant Chaudhary <sukaant.chaudhary@gmail.com>

Setting timeout to System env

---

reaper/templates/deployment.yaml
reaper/values.yaml

co-authored-by: Nathaniel Stevens <nstevens@pillartechnology.com>
relates to smartcitiesdata/reaper#88

Fix error caused by bad value

---

flair/Chart.yaml
flair/templates/_helpers.tpl
flair/templates/deployment.yaml
flair/values.yaml

co-authored-by: Scott Millard <smillard@hntb.com>

Moving flair charts to charts

---

.gitignore
odo/.helmignore
odo/Chart.yaml
odo/templates/_helpers.tpl
odo/templates/deployment.yaml
odo/values.yaml

co-authored-by: Cameron Marsh <cmarsh@pillartechnology.com>

Add odo chart

---

odo/templates/_helpers.tpl
odo/templates/deployment.yaml

co-authored-by: Cameron Marsh <cmarsh@pillartechnology.com>

Fixes typos and removes extraneous code in odo

---

valkyrie/Chart.yaml
valkyrie/templates/deployment.yaml

co-authored-by: Jake Prem <jakeprem@gmail.com>

Remove liveness probe

---

docs/index.yaml
valkyrie/Chart.yaml

co-authored-by: Jake Prem <jakeprem@gmail.com>

Version bump

---

kubernetes-data-platform/values.yaml

This will instead be overriden in the deploy repo.

revert timeout change

---

andi/templates/_helpers.tpl
andi/templates/deployment.yaml
andi/values.yaml

co-authored-by: Nathaniel Stevens <nstevens@pillartechnology.com>
Andi now needs to know about kafka to send events to the event stream.

Adding kafka connection settings to andi chart

---

carpenter/values.yaml

co-authored-by: Jake Prem <jakeprem@gmail.com>

Fix carpenter values

---

valkyrie/templates/service.yaml

smartcitiesdata/valkyrie#69
co-authored-by: Jarred Olson <jarred.olson@accenture.com>

Fixing template error

---

odo/templates/deployment.yaml
odo/values.yaml

smartcitiesdata/odo#3
co-authored-by: Nathaniel Stevens <nathaniel.scott.stevens@gmail.com>

added prometheus metrics properties for odo

---

micro-service-watchinator/Chart.yaml
micro-service-watchinator/templates/_helpers.tpl
micro-service-watchinator/templates/deployment.yaml
micro-service-watchinator/values.yaml

smartcolumbusos/watchinator#14
co-authored-by: Richard Jones <rajones@hntb.com>

Moved micro-service-watchinator charts to charts

---

micro-service-watchinator/Chart.yaml
micro-service-watchinator/values.yaml

co-authored-by: Richard Jones <rajones@hntb.com>

Setting pull policy to always for micro service watchinator

---

estuary/templates/deployment.yaml
estuary/values.yaml

[Events can be inserted into events table: Chart update for dlq](https://github.com/smartcitiesdata/smartcitiesdata/issues/344)
co-authored-by: Jessie Morris <jmorris2@pillartechnology.com>

Included dlq in Estuary charts.

---

docs/index.yaml
kubernetes-data-platform/templates/presto/worker-config.yaml
kubernetes-data-platform/values.yaml

co-authored-by: Scott Millard <smillard@hntb.com>

Fix hypen error in KDP chart

---

andi/Chart.yaml
andi/values.yaml
docs/index.yaml

smartcitiesdata/smartcitiesdata#778

Add auth0 env variables to andi

---

docs/index.yaml
vault/Chart.yaml
vault/templates/config.yaml
vault/values.yaml

Datastillery/smartcitiesdata#970
co-authored-by: Timothy Regan <tregan@pillartechnology.com>

Specify vault capabilities with access policies

---

urban-os/Chart.lock
urban-os/Chart.yaml
urban-os/values.yaml

Datastillery/smartcitiesdata#1283
co-authored by: Nicole Arruda <narruda789@gmail.com>

add raptor to urban OS

---

raptor/Chart.yaml
raptor/templates/deployment.yaml
raptor/templates/secrets.yaml
raptor/values.yaml

update raptor chart to include auth0 creds

---

urban-os/Chart.lock
urban-os/Chart.yaml

update urban-os chart with new raptor chart

---

.github/workflows/release.yml
.gitignore
charts/andi/Chart.yaml
charts/discovery-api/Chart.yaml
charts/discovery-api/templates/deployment.yaml
charts/discovery-streams/Chart.yaml
charts/discovery-ui/Chart.yaml
charts/estuary/Chart.yaml
charts/external-services/Chart.yaml
charts/flair/Chart.yaml
charts/forklift/Chart.yaml
charts/kafka/Chart.yaml
charts/kubernetes-data-platform/Chart.yaml
charts/micro-service-watchinator/Chart.yaml
charts/monitoring/Chart.yaml
charts/odo/Chart.yaml
charts/raptor/Chart.yaml
charts/reaper/Chart.yaml
charts/urban-os/Chart.lock
charts/urban-os/Chart.yaml
charts/valkyrie/Chart.yaml
charts/vault/Chart.yaml

Dependency fix

---

charts/kafka/Chart.yaml
charts/kafka/templates/kafka.yml
charts/urban-os/Chart.lock
charts/urban-os/Chart.yaml

Kafka chart fixes

---

charts/discovery-streams/Chart.yaml
charts/discovery-streams/templates/deployment.yaml
charts/discovery-streams/values.yaml
charts/forklift/Chart.yaml
charts/forklift/templates/deployment.yaml
charts/forklift/values.yaml
charts/raptor/Chart.yaml
charts/raptor/templates/deployment.yaml
charts/raptor/values.yaml
charts/reaper/Chart.yaml
charts/reaper/templates/deployment.yaml
charts/reaper/values.yaml
charts/urban-os/Chart.lock
charts/urban-os/Chart.yaml

- Adds Redis SSL chart values
- Non SSL remains default

Redis SSL Chart Values

---

charts/discovery-api/Chart.yaml
charts/discovery-api/templates/deployment.yaml
charts/discovery-api/templates/ingress.yaml
charts/discovery-api/templates/secrets.yaml
charts/discovery-api/values.yaml
charts/urban-os/Chart.lock

- Add redis config options
- Add s3 host config options
- Postgres SSL config options
- Ingress optional
- Remove stale secrets_endpoint items

Discovery API SSL Config + Stale code removal

---

charts/reaper/values.yaml
charts/urban-os/Chart.lock
charts/urban-os/values.yaml

Using a specific compatible version of reaper, and turning off alchemist

---

charts/reaper/Chart.yaml

Bumping reaper version

---

charts/urban-os/Chart.lock

Rerunning lock file

---

charts/urban-os/Chart.yaml

Bumping urbanos chart version

---

.gitignore
charts/urban-os/Chart.lock
charts/urban-os/Chart.yaml
charts/urban-os/templates/auth0-config.yaml
charts/urban-os/values.yaml

auto-generated-auth0-config

---

charts/andi/Chart.yaml
charts/andi/templates/deployment.yaml
charts/andi/values.yaml
charts/urban-os/templates/auth0-config.yaml

Chart updates to support andi in openshift

---

charts/discovery-api/Chart.yaml
charts/discovery-api/templates/service.yaml
charts/discovery-ui/Chart.yaml
charts/discovery-ui/templates/service.yaml
charts/urban-os/Chart.lock

Discovery UI openshift

---

charts/forklift/Chart.yaml
charts/forklift/templates/deployment.yaml
charts/kubernetes-data-platform/Chart.yaml
charts/kubernetes-data-platform/templates/metastore/deployment.yaml
charts/kubernetes-data-platform/values.yaml
charts/urban-os/Chart.lock

forklift chart fix and optional metastore resources

---

charts/discovery-api/Chart.yaml
charts/discovery-api/values.yaml
charts/discovery-streams/Chart.yaml
charts/discovery-streams/values.yaml
charts/urban-os/Chart.yaml

update charts repo with new raptor url

---

charts/urban-os/Chart.yaml
charts/urban-os/values.yaml

Enabling alchemist!

---

.github/pull_request_template.md
charts/urban-os/Chart.lock

Update chart lock

---

charts/andi/Chart.yaml
charts/andi/templates/deployment.yaml
charts/andi/values.yaml

feat(789): Add env variable that sets header logo

---

charts/andi/Chart.yaml
charts/andi/README.md
charts/discovery-ui/Chart.yaml
charts/discovery-ui/README.md
charts/kafka/Chart.yaml
charts/kafka/README.md
charts/urban-os/Chart.lock
charts/urban-os/Chart.yaml
charts/urban-os/README.md

The actions have been failing because a version number got repeated. Bumping everything that has had a release in the last week to hopefully fix this.

Bump several patches because the release versions had problems

---

charts/persistence/Chart.yaml
charts/persistence/values.yaml

HiveUpdate2
